### ISSUE TITLE
Clearing Dictionary

### ISSUE THREAD

**Issue by arunksoman** [varnamproject/govarnam#30]
How can I clear dictionary. Consider I trained lot of data from a large text file and things went wrong due to lot of incorrect words added to dictionary. How can I clear complete dictionary and start evrything from scratch?

**Comment by subins2000** [comment]
You can remove the dictionary DB directly. If you're on Linux do this :

```
sudo rm ~/.local/share/varnam/learnings/ml.vst.learnings*
```

The dictionary DB is just a sqlite DB. You can use software like [SQLite Browser](https://sqlitebrowser.org/) to know what's inside it.

**Comment by arunksoman** [comment]
I am closing this issue. I renamed the vst file and tried to train again. It generated a new vst file on `.local/share/varnam/learnings/ directory`.
