### ISSUE TITLE
Debian Packaging

### ISSUE THREAD

**Issue by subins2000** [varnamproject/govarnam#5]
With release of v1.5.0, the most stable version we can start with Debian packaging govarnam. The structure of packaging should be :

* Package for govarnam library (this repo)
* Package for `varnamcli` (this repo, see subfolder cli)
* Package for govarnam-ibus : https://github.com/varnamproject/govarnam-ibus
* Individual language support from https://github.com/varnamproject/schemes

End result installation:
```
sudo apt install varnamcli # govarnam will be its dependency
sudo apt install ibus-varnam # govarnam will be its dependency
sudo apt install varnam-ml # Language support for Malayalam. For adding Malayalam support
```

**Comment by subins2000** [comment]
Planning to package varnam like:

* libgovarnam: https://github.com/varnamproject/govarnam
* varnamcli: https://github.com/varnamproject/govarnam/tree/master/cli
* ibus-engine-varnam: https://github.com/varnamproject/govarnam-ibus
* varnam-language-ml: https://github.com/varnamproject/schemes/releases/tag/v1.6.0

Varnam stores a words dictionary in user's `~/.local/share/varnam/learnings`

When user types words, or import words it get stored there.

To make setup convenient for the user, when installing varnam-language-ml the package will have some words in it. On install these words should be imported to varnam. For this the import process needs to be done under user uid cause `$HOME`

What would be the way to achieve this without modifying Varnam library ? This is something specific to how `varnam-ml` is packaged so it's platform dependent.

The answer I got was that it isn't possible. The way to do this would be to make Varnam load words on first-run similar to how Firefox inits its home user directory on first startup. **I don't want this to be don in core varnam library but in a special varnam script just for linux packaging**. Here's a rough idea of that import script:

```
# varnam-setup-ml.sh
# varnam-language-ml will install words file (.vlf) in /usr/share/varnam/vlf
lastImportStatus = readfile ~/.local/share/varnam/learnings/ml.status

foreach (file in /usr/share/varnam/vlf that is not in lastImportStatus) {
  run varnamcli -s ml -import file.vlf
}
update ~/.local/share/varnam/learnings/ml.status with MD5 hash of the files just imported

# When there's a future update of `varnam-language-ml` the MD5 hash of the files in `/usr/share/varnam/vlf` would change and so import will run again on next startup
```

**Comment by naveensd101** [comment]
Hey you working on this?

**Comment by subins2000** [comment]
@naveensd101 @agx has package govarnam. Rest of it I don't think anybody has started yet, are you interested?

**Comment by agx** [comment]
> @naveensd101 @agx has packaged [govarnam](https://packages.debian.org/unstable/libs/libgovarnam1). Rest of it I don't think anybody has started yet, are you interested?

@subins2000 schemes are also done but need ftp master approval.

**Comment by naveensd101** [comment]
@subins2000 I am interested. But I am pretty new to packaging. If you have some docs, it would be great.

**Comment by subins2000** [comment]
@naveensd101 I've made an issue for you with help and relevant links https://github.com/varnamproject/govarnam-ibus/issues/9

I'm closing this issue since govarnam got packaged and the information in the issue is outdated now

**Comment by agx** [comment]
Note that I welcome comaintainers in Debian, currently sorting out if we put this under the go team or input-method team umbrella there.
